[package]
name = "pass"
description = "Rewrite of pass in Rust"
license = "GPL-2.0-or-later"
version = "0.1.0"
authors = ["Gregory Anders <greg@gpanders.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3"
colored = "2"
